name: Daily Check-in

on:
  schedule:
    - cron: '0 21-23,0-16/2 * * *'  # 每2小时触发一次（北京时间 5:00-24:00）
    - cron: '0 17-20/4 * * *'       # 每4小时触发一次（北京时间 1:00-4:00）
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps firefox

      - name: Execute script
        id: run_script  # 添加 ID 以便后续引用
        continue-on-error: true  # 允许脚本失败继续执行
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          if python main.py > output.txt 2>&1; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - name: Send PUSH+ Notification
        env:
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        if: always()
        run: |
          if [ "${{ steps.run_script.outputs.status }}" = "success" ]; then
            STATUS="✅ 成功"
            CONTENT=$(cat output.txt || echo "签到完成")
          else
            STATUS="❌ 失败"
            CONTENT="签到脚本执行失败，请检查日志\n\n$(cat output.txt || echo '未能获取详细错误信息')"
          fi
          
          curl -s "http://www.pushplus.plus/send" \
          -H "Content-Type: application/json" \
          -d "{
            \"token\": \"${{ env.PUSH_PLUS_TOKEN }}\",
            \"title\": \"linux.do浏览帖子：${STATUS}\",
            \"content\": \"${CONTENT}\",
            \"template\": \"markdown\"
          }"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6
